### ISSUE TITLE
Bayescan_2.1 not found

### ISSUE THREAD

**Issue by juance100** [fbalao/AFLPsim#1]
When trying to run bayescan() under linux (Ubuntu) I get the message 
sh: 1: bayescan_2.1: not found
[1] "Bayescan_2.1 not found"
I tried to set the working directory in the folder where Bayescan is installed, but the problem is not solved. 
Is there a way to tell R where bayescan is?
Thank you in advance

**Comment by fbalao** [comment]
Dear user,

Thanks for you email. You should set the working directory but you also 
need to call the binary file. You should have execute permission for 
your user. Here a example.

outbayes<-bayescan(hybrids, filename="bayescanresults", nbp=10, 
pilot=50, burn=100, 
exec="/home/fbalao/Programas/BayeScan2.1/binaries/BayeScan2.1_linux64bits")

Let me know  if this fixes things.

Fran

El 08/10/15 a las 19:11, juance100 escribió:

> When trying to run bayescan() under linux (Ubuntu) I get the message
> sh: 1: bayescan_2.1: not found
> [1] "Bayescan_2.1 not found"
> I tried to set the working directory in the folder where Bayescan is 
> installed, but the problem is not solved.
> Is there a way to tell R where bayescan is?
> Thank you in advance
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/fbalao/AFLPsim/issues/1.

## 

Francisco Balao Robles, PhD
Department Plant Biology and Ecology
Faculty of Biology, University of Seville
Reina Mercedes nº 6
41012 SEVILLE
SPAIN

Phone number: +34954559887

e-Mail: fbalao@us.es

http://personal.us.es/fbalao/index.html

**Comment by juance100** [comment]
Thank for your answer. The "exec" argument fixes the problem.
